# Generated by Django 5.0 on 2023-12-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_authors_birthdate_alter_authors_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birthDate',
            field=models.CharField(max_length=255),
        ),
    ]
