# Generated by Django 5.0 on 2023-12-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_authors_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
