# Generated by Django 5.0 on 2023-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_authors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='birthCity',
            field=models.CharField(default='Tomsk', max_length=255),
            preserve_default=False,
        ),
    ]
